### ISSUE TITLE
[DOC]Add an import statement to docstring examples wherever missing

### ISSUE THREAD

**Issue by JonathanBechtel** [sktime/sktime#4400]
#### Describe the issue linked to the documentation
There are instances in the sktime documentation where no import statement is given for a particular example.  This is problematic since it prevents a user from being able to quickly copy & paste the example from the docstring to see how something works.  

#### Suggest a potential alternative/fix
If you find an example where the sktime example does not include the actual import of said sktime element, please add it to the docstring and submit a pull request for it and link to this pull request

**Comment by fkiraly** [comment]
yes, agreed, great user facing idea!

Adding the "good first issue" tag.

**Comment by SSROCKS30** [comment]
@fkiraly I fixed some part of this issue in PR #7327. Please do check it out.

**Comment by aparajitaks** [comment]
Hi, I would like to work on this issue as a first contribution.

I understand that several missing import statements have already been fixed in previous PRs, so I plan to look for other docstring examples where the import is still missing and add them.

Please let me know if this approach is okay, or if there is a specific module I should check.

**Comment by Kush5699** [comment]
I am working on this as my entrance-task contribution for GSoC 2026.
Plan: add missing import lines in docstring examples for selected estimators, and reference this issue in PR.

**Comment by bhrigushi** [comment]
Hi! I'd like to contribute to this issue as part of my ESoC 2026 application. I'll look for missing import statements in docstring examples and submit a PR.
