### ISSUE TITLE
[BUG] Use of private sklearn methods causing issues

### ISSUE THREAD

**Issue by ngupta23** [sktime/sktime#4669]
**Describe the bug**

The following code in sktime calls a provate module in sklearn. This is causing sporadic issues in pycaret. 

https://github.com/sktime/sktime/blob/b1a6c0d68a66f779aa0dffcea8ac2fc685613715/sktime/forecasting/compose/_bagging.py#L196-L197C76

**To Reproduce**

I have not been able to reproduce this myself, but several users have reported this issue recently.

- https://github.com/pycaret/pycaret/issues/3569
- https://github.com/pycaret/pycaret/issues/3582

![image](https://github.com/sktime/sktime/assets/33585645/937421cb-3a14-4a39-bbf0-7974072dfcd1)

**Expected behavior**
Would expect the imports to go through. Can we somehow avoid using private sklearn modules in sktime code in this instance.

**Additional context**

**Versions**
<details>

</details>

**Comment by fkiraly** [comment]
sigh - I thought we had eliminated all private imports of `sklearn` methods already, e.g., https://github.com/sktime/sktime/issues/2631

I suppose this fell through the radar since it's not a private function but a private module, so it won't be caught by a search-all for `import _sthsth`.

I've opened a general issue for detection and testing here: https://github.com/sktime/sktime/issues/4670

And let's deal with the specific bugs you reported in this issue, @ngupta23.

**Comment by fkiraly** [comment]
@ngupta23, question: I'm not sure how to reproduce or test this. Do you have any insights from your users who experience problems, e.g., is there a piece of code that sporadically fails, or similar? What dependency conditions does this occur under?

**Comment by fkiraly** [comment]
started here, @ngupta23: https://github.com/sktime/sktime/pull/4672

know any other instances?

**Comment by ngupta23** [comment]
Thanks. That is the only one I am aware of right now. If I encounter anything else, I will let you know.

**Comment by ngupta23** [comment]
@fkiraly Is this issue closed since the PR is merged?

**Comment by fkiraly** [comment]
there are other, unresolved instances of private imports:

* `_partition_estimators` imports
* `from sklearn.ensemble._forest import`-s

That's why it hasn't been so clear to me whether to close this or not.

Maybe we should close this as it originally related to the random state and open a tracker issue for the others?

**Comment by ngupta23** [comment]
Yes, it would be better to get this in the next release (and address others as needed later). We have now seen 4 users report this error on pycaret (were 2 when I opened it)

**Comment by fkiraly** [comment]
sorry for that - have you checked whether the bugfix would solve it, e.g., by prerelease testing? Because if not, we need to drill deeper.

Btw, I remember how: the actual reason why I kept this open is that we need confirmation that this indeed resolves your issue, @ngupta23

**Comment by fkiraly** [comment]
Btw, @ngupta23, in the new bug reports, is there anything we could use as a reproducible failure case and a regression test?

**Comment by fkiraly** [comment]
& FYI, 0.19.2 is scheduled for the next days if all goes well.

**Comment by ngupta23** [comment]
> in the new bug reports, is there anything we could use as a reproducible failure case and a regression test?

No, I have been unable to do it. See https://github.com/pycaret/pycaret/issues/3569#issuecomment-1594827082

**Comment by fkiraly** [comment]
have you been able to do a prerelease test whether current `sktime` `main` fixes it?

If you're not sure how, here's how I (ab)use the CI for testing with prereleases of `sklearn` and `skbase`:
* https://github.com/sktime/sktime/pull/4611
* https://github.com/sktime/sktime/pull/4534

**Comment by fkiraly** [comment]
Why I'm asking: there's a few days until 0.19.2, so if it *doesn't* fix it, we lose 2-3 weeks or so until it gets fixed (assuming the best, i.e., that we can quickly find the actual error once we have the information that it's not this).

**Comment by ngupta23** [comment]
I have posted the request to the original posters to verify the failure by installing sktime from git

https://github.com/pycaret/pycaret/issues/3605#issuecomment-1595406952
https://github.com/pycaret/pycaret/issues/3569#issuecomment-1595406021
https://github.com/pycaret/pycaret/issues/3582#issuecomment-1595407578

**Comment by ngupta23** [comment]
See https://github.com/pycaret/pycaret/issues/3569#issuecomment-1602729600 for a potential solution.

**Comment by fkiraly** [comment]
Is this resolved with 0.19.2, @ngupta23?

**Comment by ngupta23** [comment]
Don't know. None of the OPs have responded.

**Comment by fkiraly** [comment]
well, that's usually a cautiously good sign if people stop complaining...

**Comment by ngupta23** [comment]
Out of the three who reported this issue, a couple responded and said that the upgrade did not resolve the issue (although did not provide the new error message).

https://github.com/pycaret/pycaret/issues/3582#issuecomment-1607772668 - No response
https://github.com/pycaret/pycaret/issues/3569#issuecomment-1603527436 - Incomplete response
https://github.com/pycaret/pycaret/issues/3605#issuecomment-1614745959 - Incomplete response

In the same threads, a couple of them reported the issue as resolved once they upgraded the ``threadpoolctl` package

```
!pip install --upgrade threadpoolctl
```

I think that the upgrade will at least resolve the previously reported error in this issue, so maybe you can close this for now. If it persists, we can evaluate it and reopen another issue.

**Comment by ngupta23** [comment]
Summary of Possible Solutions:

- Upgrade `threadpool`: `pip install --upgrade threadpoolctl`
- Upgrade `sktime`: `pip install sktime >= 0.19.2`

**Comment by fkiraly** [comment]
ok, thanks for the update!
